# Generated by Django 4.2.23 on 2025-07-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_materialcategory_alter_materialitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.materialcategory'),
        ),
    ]
