# Generated by Django 4.2.23 on 2025-07-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_materialcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'ordering': ('order',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='materialcategory',
            old_name='display_order',
            new_name='order',
        ),
    ]
