# Generated by Django 4.2.23 on 2025-07-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_materialcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialitem',
            options={'ordering': ('order',), 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукции'},
        ),
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ('order',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='styleitem',
            options={'ordering': ('order',), 'verbose_name': 'Стиль', 'verbose_name_plural': 'Стили'},
        ),
    ]
