# Generated by Django 4.2.23 on 2025-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_materialitem_options_alter_projectitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
