# Generated by Django 4.2.23 on 2025-07-14 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_materialcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcategory',
            name='image',
            field=models.ImageField(blank=True, default='default_foto.png', upload_to='category_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic'])], verbose_name='Фото категории'),
        ),
    ]
