# Generated by Django 4.2.23 on 2025-07-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_partners_alter_serviceitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок'),
        ),
    ]
