# Generated by Django 4.2.23 on 2025-07-15 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_projectitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': 'Категория материала', 'verbose_name_plural': 'Категории материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialitem',
            options={'ordering': ('order',), 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ['order'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.materialcategory', verbose_name='Категория'),
        ),
    ]
