# Generated by Django 4.2.23 on 2025-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_materialcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='styleitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='styleitem',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='styleitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название стиля'),
        ),
        migrations.AddField(
            model_name='styleitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название стиля'),
        ),
    ]
