# Generated by Django 4.2.23 on 2025-07-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_materialcategory_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materials/')),
            ],
        ),
        migrations.AddField(
            model_name='materialitem',
            name='additional_images',
            field=models.ManyToManyField(blank=True, null=True, to='main.images'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='main.images', verbose_name='Доп. изображения'),
        ),
    ]
