# Generated by Django 4.2.23 on 2025-07-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_images_materialitem_additional_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='materials/', verbose_name='Доп. Фотографии'),
        ),
    ]
