# Generated by Django 4.2.23 on 2025-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='square_meters',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Площадь (м²)'),
        ),
    ]
