# Generated by Django 4.2.23 on 2025-07-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_projectitem_square_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Доп. Фотографии')),
            ],
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='MaterialImages',
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='main.projectimages', verbose_name='Доп. изображения'),
        ),
    ]
