# Generated by Django 4.2.23 on 2025-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_projectimages_rename_images_materialimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialimages',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='projectimages',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='main.materialimages'),
        ),
    ]
