# Generated by Django 4.2.23 on 2025-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_materialimages_name_alter_projectimages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
    ]
