# Generated by Django 4.2.23 on 2025-07-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_serviceitem_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialimages',
            options={'ordering': ('-id',), 'verbose_name': 'Фото материала', 'verbose_name_plural': 'Фотографии материал'},
        ),
        migrations.AlterModelOptions(
            name='projectimages',
            options={'ordering': ('-id',), 'verbose_name': 'Фото проекта', 'verbose_name_plural': 'Фотографии проекта'},
        ),
    ]
