# Generated by Django 4.2.23 on 2025-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_materialimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcategory',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='materialitem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='styleitem',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='styleitem',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название стиля'),
        ),
    ]
