# Generated by Django 4.2.23 on 2025-07-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_materialcategory_description_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'ordering': ('order',), 'verbose_name': 'Категория материала', 'verbose_name_plural': 'Категории материалов'},
        ),
    ]
