# Generated by Django 4.2.23 on 2025-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0024_alter_materialcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
