# Generated by Django 4.2.23 on 2025-10-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0025_partners_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guaranteeitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='guaranteeitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True,
                                              verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True,
                                              verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='category',
            field=models.CharField(
                choices=[('commercial', 'Коммерческие помещения'), ('residential', 'Жилые помещения'),
                         ('other', 'Другое')], db_index=True, default='other', max_length=20,
                verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='styleitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddIndex(
            model_name='guaranteeitem',
            index=models.Index(fields=['order'], name='guarantee_order_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcategory',
            index=models.Index(fields=['order'], name='mat_cat_order_idx'),
        ),
        migrations.AddIndex(
            model_name='materialitem',
            index=models.Index(fields=['order', 'category'], name='mat_item_order_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='partners',
            index=models.Index(fields=['order'], name='partners_order_idx'),
        ),
        migrations.AddIndex(
            model_name='projectitem',
            index=models.Index(fields=['category', 'order'], name='proj_cat_order_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['order', 'id'], name='service_order_id_idx'),
        ),
        migrations.AddIndex(
            model_name='styleitem',
            index=models.Index(fields=['order'], name='style_order_idx'),
        ),
    ]
